# Generated by Django 3.2.3 on 2021-06-03 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, db_column='CartID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mystore.cart'),
        ),
    ]
