# Generated by Django 3.2.3 on 2021-06-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='isProcessed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
