# Generated by Django 3.2.3 on 2021-06-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0002_auto_20210603_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='memberid',
            new_name='member',
        ),
    ]
