# Generated by Django 3.2.3 on 2021-06-17 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0002_feedback_isprocessed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPBank',
            fields=[
                ('bank_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mystore.bank')),
            ],
            bases=('mystore.bank',),
        ),
        migrations.CreateModel(
            name='VietcomBank',
            fields=[
                ('bank_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mystore.bank')),
            ],
            bases=('mystore.bank',),
        ),
        migrations.CreateModel(
            name='VietinBank',
            fields=[
                ('bank_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mystore.bank')),
            ],
            bases=('mystore.bank',),
        ),
    ]
