# Generated by Django 3.2.3 on 2021-06-03 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0003_rename_memberid_customer_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='addressid',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='customerid',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='orderid',
            new_name='order',
        ),
    ]
