# Generated by Django 3.2.3 on 2021-06-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0004_auto_20210603_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='itemid',
            new_name='item',
        ),
    ]
