# Generated by Django 3.2.3 on 2021-06-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0004_auto_20210618_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=1000, null=True),
        ),
    ]
