# Generated by Django 3.2.3 on 2021-06-17 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0005_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='respone',
            name='member',
            field=models.ForeignKey(db_column='MemberID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mystore.member'),
        ),
    ]
