# Generated by Django 3.2.3 on 2021-06-17 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0006_respone_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respone',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='respone',
            name='created_date',
            field=models.DateTimeField(blank=True, db_column='Created_date', default=datetime.datetime.now, null=True),
        ),
    ]
