# Generated by Django 3.2.3 on 2021-06-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0006_auto_20210603_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='productid',
            new_name='product',
        ),
    ]
