# Generated by Django 3.2.3 on 2021-06-04 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0007_rename_productid_item_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(db_column='ItemID', on_delete=django.db.models.deletion.CASCADE, to='mystore.item'),
        ),
    ]
