# Generated by Django 3.2.3 on 2021-06-18 02:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0007_auto_20210618_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportBill',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(blank=True, db_column='Created_date', default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'export_bill',
            },
        ),
        migrations.CreateModel(
            name='ExportProduct',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('qty', models.IntegerField(db_column='Qty')),
                ('export_bill', models.ForeignKey(db_column='Import_billID', on_delete=django.db.models.deletion.DO_NOTHING, to='mystore.exportbill')),
                ('product', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='mystore.product')),
            ],
            options={
                'db_table': 'export_product',
            },
        ),
        migrations.CreateModel(
            name='ImportBill',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(blank=True, db_column='Created_date', default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'import_bill',
            },
        ),
        migrations.RemoveField(
            model_name='importproduct',
            name='import_file',
        ),
        migrations.RemoveField(
            model_name='warehousestaff',
            name='import_file',
        ),
        migrations.DeleteModel(
            name='ImportFile',
        ),
        migrations.AddField(
            model_name='importbill',
            name='warehouseStaff',
            field=models.ForeignKey(db_column='warehouse_staff_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mystore.warehousestaff'),
        ),
        migrations.AddField(
            model_name='exportbill',
            name='warehouseStaff',
            field=models.ForeignKey(db_column='warehouse_staff_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mystore.warehousestaff'),
        ),
        migrations.AddField(
            model_name='importproduct',
            name='import_bill',
            field=models.ForeignKey(db_column='Import_billID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mystore.importbill'),
        ),
    ]
