# Generated by Django 3.2.3 on 2021-06-18 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0008_auto_20210618_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respone',
            name='comment',
            field=models.ForeignKey(db_column='CommentID', on_delete=django.db.models.deletion.CASCADE, to='mystore.comment'),
        ),
    ]
