# Generated by Django 3.2.3 on 2021-06-18 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0010_alter_feedback_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('qty', models.IntegerField(db_column='Qty')),
                ('item', models.ForeignKey(db_column='ItemID', on_delete=django.db.models.deletion.CASCADE, to='mystore.item')),
                ('order', models.ForeignKey(db_column='OrderId', on_delete=django.db.models.deletion.CASCADE, to='mystore.order')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
    ]
